"""
QMIX — Monotonic value decomposition for cooperative MARL credit assignment.
=============================================================================
Rashid, T., Samvelyan, M., De Witt, C.S., Farquhar, G., Foerster, J., &
Whiteson, S. (2018). "QMIX: Monotonic Value Function Factorisation for Deep
Multi-Agent Reinforcement Learning." Proceedings of ICML 2018, PMLR 80,
pp. 4295-4304.  arXiv:1803.11605.

Key insight (Rashid et al. 2018, Theorem 1):
  Q_tot(tau, a) = f_mix(Q_1(tau_1,a_1), ..., Q_n(tau_n,a_n); s)
  Monotonicity: dQ_tot/dQ_i >= 0 for all i
  => argmax_a Q_tot == {argmax_{a_i} Q_i}  for each agent i independently
  => Centralised training with decentralised execution (CTDE) is tractable.

Implementation:
  - Hypernetworks (Ha & Schmidhuber 2016) generate non-negative mixing weights
    from the global state, enforcing monotonicity via absolute value activation.
  - Each AIGIS RL agent (Firefighter, Rescuer, Commander) maintains an
    individual Q-network whose Q-values are then mixed by QMIXMixer.
  - The mixing network is only used during training; agents execute
    independently at inference time (CTDE paradigm).

Usage in training loop (replace per-role PPO critic with QMIX):
  mixer   = QMIXMixer(n_agents=3, global_state_dim=72, mixing_embed_dim=32)
  q_vals  = torch.stack([q_ff, q_rsc, q_cmd], dim=1)  # shape (B, 3)
  q_tot   = mixer(q_vals, global_state)                # shape (B, 1)
  loss    = F.mse_loss(q_tot, target_q)

References:
  Rashid et al. (2018) — QMIX  arXiv:1803.11605
  Ha, D. & Schmidhuber, J. (2016). "HyperNetworks." ICLR 2017.
    arXiv:1609.09106.  [Hypernetwork that generates mixing weights from state.]
  Samvelyan, M. et al. (2019). "The StarCraft Multi-Agent Challenge." AAMAS.
    arXiv:1902.04043.  [Validated QMIX on cooperative benchmarks.]
"""
from __future__ import annotations
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from typing import Optional


class QMIXMixer(nn.Module):
    """
    Monotonic mixing network for QMIX.

    Takes per-agent Q-values and a global state vector; outputs a single
    Q_tot scalar.  Mixing weights are generated by a hypernetwork conditioned
    on the global state and are constrained to be non-negative (Rashid et al.
    2018, Eq. 3) so that monotonicity holds.

    Architecture follows Rashid et al. (2018) Appendix B:
      - Hypernetwork 1: state → weights of first mixing layer (n_agents × embed)
      - Hypernetwork 2: state → weights of second mixing layer (embed → 1)
      - Bias hypernetwork: state → biases for each layer
      - All weight outputs use absolute value to ensure non-negativity.

    Hyperparameters follow the original QMIX paper defaults (Table 1):
      mixing_embed_dim = 32   (Rashid et al. 2018 use 32 for SC2 tasks)
    """

    def __init__(
        self,
        n_agents: int          = 3,
        global_state_dim: int  = 72,
        mixing_embed_dim: int  = 32,
    ):
        """
        Args:
            n_agents:          number of cooperative agents (3 for AIGIS)
            global_state_dim:  dimension of concatenated global state (72)
            mixing_embed_dim:  hidden dimension of mixing network
                               (Rashid et al. 2018 Table 1: 32 units)
        """
        super().__init__()
        self.n_agents         = n_agents
        self.global_state_dim = global_state_dim
        self.embed_dim        = mixing_embed_dim

        # Hypernetwork 1: state → W1 weights (shape: n_agents × embed_dim)
        # Absolute value output enforces non-negativity (Rashid 2018, Eq. 3).
        self.hyper_w1 = nn.Sequential(
            nn.Linear(global_state_dim, mixing_embed_dim),
            nn.ReLU(),
            nn.Linear(mixing_embed_dim, n_agents * mixing_embed_dim),
        )

        # Hypernetwork 2: state → W2 weights (shape: embed_dim × 1)
        self.hyper_w2 = nn.Sequential(
            nn.Linear(global_state_dim, mixing_embed_dim),
            nn.ReLU(),
            nn.Linear(mixing_embed_dim, mixing_embed_dim),
        )

        # Bias networks (biases are unrestricted — do not affect monotonicity)
        self.hyper_b1 = nn.Linear(global_state_dim, mixing_embed_dim)
        # Final bias: small MLP following Rashid et al. (2018) Appendix B
        self.hyper_b2 = nn.Sequential(
            nn.Linear(global_state_dim, mixing_embed_dim),
            nn.ReLU(),
            nn.Linear(mixing_embed_dim, 1),
        )

    def forward(self, agent_qs: torch.Tensor, state: torch.Tensor) -> torch.Tensor:
        """
        Mix per-agent Q-values into a single Q_tot.

        Args:
            agent_qs: per-agent Q-values, shape (batch, n_agents)
            state:    global state vector, shape (batch, global_state_dim)

        Returns:
            q_tot: shape (batch, 1)

        Monotonicity is guaranteed because W1 and W2 are passed through
        torch.abs() before the matrix multiply (Rashid et al. 2018, Eq. 3).
        """
        batch = agent_qs.size(0)
        qs    = agent_qs.view(batch, 1, self.n_agents)  # (B, 1, n)

        # --- First mixing layer ---
        # W1: (B, n_agents, embed) — non-negative via abs()
        w1 = torch.abs(self.hyper_w1(state)).view(batch, self.n_agents, self.embed_dim)
        b1 = self.hyper_b1(state).view(batch, 1, self.embed_dim)

        hidden = F.elu(torch.bmm(qs, w1) + b1)   # (B, 1, embed)

        # --- Second mixing layer ---
        # W2: (B, embed, 1) — non-negative via abs()
        w2 = torch.abs(self.hyper_w2(state)).view(batch, self.embed_dim, 1)
        b2 = self.hyper_b2(state).view(batch, 1, 1)

        q_tot = torch.bmm(hidden, w2) + b2        # (B, 1, 1)
        return q_tot.view(batch, 1)               # (B, 1)


def compute_qmix_loss(
    agent_qs:    torch.Tensor,
    target_qs:   torch.Tensor,
    global_state: torch.Tensor,
    mixer:       QMIXMixer,
    gamma:       float = 0.99,
    rewards:     Optional[torch.Tensor] = None,
    dones:       Optional[torch.Tensor] = None,
) -> torch.Tensor:
    """
    Compute QMIX TD loss for one training batch.

    L = E[(r + gamma * max_{a'} Q_tot(s', a') - Q_tot(s, a))^2]

    Rashid et al. (2018) Eq. 6 — the centralised Q_tot target replaces
    the per-agent returns, giving a cooperative credit assignment signal.

    Args:
        agent_qs:      per-agent Q(s,a) at current step, (B, n_agents)
        target_qs:     per-agent Q(s',a') target (max over next actions), (B, n_agents)
        global_state:  s,  shape (B, global_state_dim)
        mixer:         QMIXMixer instance
        gamma:         discount factor (0.99 follows Schulman et al. 2017)
        rewards:       team reward r_t, (B, 1)  — summed across agents
        dones:         episode done flag, (B, 1)

    Returns:
        Scalar MSE loss.
    """
    q_tot       = mixer(agent_qs, global_state)        # (B, 1)
    with torch.no_grad():
        q_tot_target = mixer(target_qs, global_state)  # (B, 1)
        if rewards is not None and dones is not None:
            target = rewards + gamma * q_tot_target * (1.0 - dones.float())
        else:
            target = q_tot_target

    return F.mse_loss(q_tot, target)
